### ISSUE TITLE
Parciais da PTAX

### ISSUE THREAD

**Issue by daviriani** [open-bacen/bancocentralbrasil#16]
Bom dia!
É possível coletar as parciais de uma data específica da PTAX por horário, conforme abaixo:

![image](https://user-images.githubusercontent.com/55510334/103907171-af112e80-50df-11eb-8f30-7ec9f9de66cb.png)

Obrigado e parabéns pelo trabalho!
Abraço,
Davi

**Comment by leogregianin** [comment]
Bom dia @daviriani. Que bom que gostou.

Fantástica sua ideia, mas não para esse projeto. Nesse projeto busca a cotação em tempo real. 

Criei esse outro projeto (https://github.com/open-bacen/cotacao-diaria-dolar) que fará o que você quer e usa a fonte de dados oficial do Banco Central.

Hoje o projeto busca a cotação por dia e por período e vou adicionar mais formas de pesquisa como a abertura e intermediária conforme a documentação deles [aqui](https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/swagger-ui3#).

**Comment by daviriani** [comment]
Ótimo Leonardo!! Maravilha! Parabéns pelo trabalho.
Testei aqui e as cotações ainda não incluem as cotações intermediárias
certo?
Estou utilizando as cotações intradiárias da PTAX para criação de
estratégias de trading com dólar futuro.
Muito obrigado pelo seu retorno.
Sucesso e um grande abraço,
Davi

Em qui., 7 de jan. de 2021 às 18:27, Leonardo Gregianin <
notifications@github.com> escreveu:
