### ISSUE TITLE
"AttributeError" na recuperação de taxas

### ISSUE THREAD

**Issue by agrezende** [open-bacen/bancocentralbrasil#17]
As consultas às páginas do BACEN utilizadas neste projeto ora retornam valores com "," (vírgula), ora com "." (ponto), como em 1,90 ou 1.90. A cada "refresh" de uma determinada página (ou a cada execução do código), não é determinístico o retorno de valores com ponto ou com vírgula.
Quando o valor retornado possui "." (ponto), as expressões regulares não darão "match", e irão resultar na exceção 'AttributeError' (pois a propriedade 'group' não estará definida).

```
/usr/local/lib/python3.7/dist-packages/bc/bancocentral.py in get_acumulada_tax(self)
     60     def get_acumulada_tax(self):
     61         inflacao = cleanContent(self.req.content.decode('utf-8'))
---> 62         tax = re.search(r'<div id=label>Acumulada</div><div id=rate><div id=value>(\d*\,?\d+)</div>', inflacao).group(1)
     63         return float(tax.replace(',','.'))
     64 

AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by leogregianin** [comment]
Fixed 66190a27bcddfa159b5a998fa43da40de9f68079
