### ISSUE TITLE
Usar API XML ou JSON ao invés do feed RSS

### ISSUE THREAD

**Issue by correa** [open-bacen/bancocentralbrasil#34]
Olá. Parabéns pelo projeto, estou usando para atualizar cotação do dólar. Seria interessante disponibilizar outros índices como IGP-M que estão disponíveis via API. Tem um vídeo explicando como acessar essa API usando um módulo Python chamado panda: https://ricospeloacaso.com.br/como-acessar-a-base-de-dados-do-banco-central-do-brasil-com-python-python-para-investimentos-10/

Seria interessante usar este método de busca das informações pois assim é possível obter muitos outros indicadores econômicos que são gerados ou consolidados pelo Banco Central.

**Comment by leogregianin** [comment]
Olá @correa, [esse outro projeto](https://github.com/open-bacen/cotacao-diaria-dolar) desta mesma [org](https://github.com/open-bacen) usa a API aberta do Bacen.
